In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
!pip install sklearn#import ML library

ERROR: Invalid requirement: 'sklearn#import'

In [5]:
csv_import=pd.read_csv("HousePrices.csv")# import csv file from the file directory

In [6]:
csv_import

,Id,Dwell_Type,Zone_Class,LotFrontage,LotArea,Road_Type,Alley,Property_Shape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Property_Sale_Price
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2068,942,60,RL,NaN,8755,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,6,2009,WD,Normal,214000
2069,943,90,RL,63.0,7711,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,Oth,Abnorml,150000
2070,944,90,RL,313.0,25000,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,143000
2071,945,20,RL,52.0,14375,Pave,NaN,IR1,Lvl,NoSeWa,...,0,NaN,NaN,NaN,0,1,2009,COD,Abnorml,137500
2072,946,50,RM,98.0,8820,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnWw,NaN,0,9,2009,WD,Normal,124900

In [7]:
csv_import.isnull().sum()#check for th null values

Id                       0
Dwell_Type               0
Zone_Class               0
LotFrontage            320
LotArea                  0
                      ...
MoSold                   0
YrSold                   0
SaleType                 0
SaleCondition            0
Property_Sale_Price      0
Length: 81, dtype: int64

In [8]:
a=csv_import.columns[csv_import.isnull().any()]
csv_import[a].isnull().sum()
# to view all the null values in the data

LotFrontage      320
Alley           1944
MasVnrType        14
MasVnrArea        14
BsmtQual          59
BsmtCond          59
BsmtExposure      61
BsmtFinType1      59
BsmtFinType2      60
Electrical         1
FireplaceQu      988
GarageType       113
GarageYrBlt      113
GarageFinish     113
GarageQual       113
GarageCond       113
PoolQC          2065
Fence           1669
MiscFeature     1993
dtype: int64

In [9]:
csv_import.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073 entries, 0 to 2072
Data columns (total 81 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   2073 non-null   int64
 1   Dwell_Type           2073 non-null   int64
 2   Zone_Class           2073 non-null   object
 3   LotFrontage          1753 non-null   float64
 4   LotArea              2073 non-null   int64
 5   Road_Type            2073 non-null   object
 6   Alley                129 non-null    object
 7   Property_Shape       2073 non-null   object
 8   LandContour          2073 non-null   object
 9   Utilities            2073 non-null   object
 10  LotConfig            2073 non-null   object
 11  LandSlope            2073 non-null   object
 12  Neighborhood         2073 non-null   object
 13  Condition1           2073 non-null   object
 14  Condition2           2073 non-null   object
 15  Dwelling_Type        2073 non-null   object
 16  HouseStyle           2073 non-null   object
 17  OverallQual          2073 non-null   int64
 18  OverallCond          2073 non-null   int64
 19  YearBuilt            2073 non-null   int64
 20  YearRemodAdd         2073 non-null   int64
 21  RoofStyle            2073 non-null   object
 22  RoofMatl             2073 non-null   object
 23  Exterior1st          2073 non-null   object
 24  Exterior2nd          2073 non-null   object
 25  MasVnrType           2059 non-null   object
 26  MasVnrArea           2059 non-null   float64
 27  ExterQual            2073 non-null   object
 28  ExterCond            2073 non-null   object
 29  Foundation           2073 non-null   object
 30  BsmtQual             2014 non-null   object
 31  BsmtCond             2014 non-null   object
 32  BsmtExposure         2012 non-null   object
 33  BsmtFinType1         2014 non-null   object
 34  BsmtFinSF1           2073 non-null   int64
 35  BsmtFinType2         2013 non-null   object
 36  BsmtFinSF2           2073 non-null   int64
 37  BsmtUnfSF            2073 non-null   int64
 38  TotalBsmtSF          2073 non-null   int64
 39  Heating              2073 non-null   object
 40  HeatingQC            2073 non-null   object
 41  CentralAir           2073 non-null   object
 42  Electrical           2072 non-null   object
 43  1stFlrSF             2073 non-null   int64
 44  2ndFlrSF             2073 non-null   int64
 45  LowQualFinSF         2073 non-null   int64
 46  GrLivArea            2073 non-null   int64
 47  BsmtFullBath         2073 non-null   int64
 48  BsmtHalfBath         2073 non-null   int64
 49  FullBath             2073 non-null   int64
 50  HalfBath             2073 non-null   int64
 51  BedroomAbvGr         2073 non-null   int64
 52  KitchenAbvGr         2073 non-null   int64
 53  KitchenQual          2073 non-null   object
 54  TotRmsAbvGrd         2073 non-null   int64
 55  Functional           2073 non-null   object
 56  Fireplaces           2073 non-null   int64
 57  FireplaceQu          1085 non-null   object
 58  GarageType           1960 non-null   object
 59  GarageYrBlt          1960 non-null   float64
 60  GarageFinish         1960 non-null   object
 61  GarageCars           2073 non-null   int64
 62  GarageArea           2073 non-null   int64
 63  GarageQual           1960 non-null   object
 64  GarageCond           1960 non-null   object
 65  PavedDrive           2073 non-null   object
 66  WoodDeckSF           2073 non-null   int64
 67  OpenPorchSF          2073 non-null   int64
 68  EnclosedPorch        2073 non-null   int64
 69  3SsnPorch            2073 non-null   int64
 70  ScreenPorch          2073 non-null   int64
 71  PoolArea             2073 non-null   int64
 72  PoolQC               8 non-null      object
 73  Fence                404 non-null    object
 74  MiscFeature          80 non-null     object
 75  MiscVal              2073 non-null   int64
 76  MoSold               2073 non-null   int64
 77  YrSold               2073 non-null   int64
 78  SaleType             2073 non-null   object
 79  SaleCondition        2073 non-null   object
 80  Property_Sale_Price  2073 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 1.3+ MB

In [10]:
#fill up the null values by the mean

In [11]:
csv_import["LotFrontage"].fillna((csv_import["LotFrontage"].mean()),inplace=True)
csv_import
#LotFrontage null values filled with mean

,Id,Dwell_Type,Zone_Class,LotFrontage,LotArea,Road_Type,Alley,Property_Shape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Property_Sale_Price
0,1,60,RL,65.000000,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.000000,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.000000,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.000000,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.000000,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2068,942,60,RL,72.056475,8755,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,6,2009,WD,Normal,214000
2069,943,90,RL,63.000000,7711,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,Oth,Abnorml,150000
2070,944,90,RL,313.000000,25000,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,143000
2071,945,20,RL,52.000000,14375,Pave,NaN,IR1,Lvl,NoSeWa,...,0,NaN,NaN,NaN,0,1,2009,COD,Abnorml,137500
2072,946,50,RM,98.000000,8820,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnWw,NaN,0,9,2009,WD,Normal,124900

In [12]:
csv_import["MasVnrArea"].fillna((csv_import["MasVnrArea"].mean()),inplace=True)
csv_import
#MasVnrArea filled null values with mean

,Id,Dwell_Type,Zone_Class,LotFrontage,LotArea,Road_Type,Alley,Property_Shape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Property_Sale_Price
0,1,60,RL,65.000000,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.000000,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.000000,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.000000,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.000000,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2068,942,60,RL,72.056475,8755,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,6,2009,WD,Normal,214000
2069,943,90,RL,63.000000,7711,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,Oth,Abnorml,150000
2070,944,90,RL,313.000000,25000,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,143000
2071,945,20,RL,52.000000,14375,Pave,NaN,IR1,Lvl,NoSeWa,...,0,NaN,NaN,NaN,0,1,2009,COD,Abnorml,137500
2072,946,50,RM,98.000000,8820,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnWw,NaN,0,9,2009,WD,Normal,124900

In [13]:
property_data=pd.DataFrame(csv_import)#convert the csv into DF

In [14]:
property_data

,Id,Dwell_Type,Zone_Class,LotFrontage,LotArea,Road_Type,Alley,Property_Shape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Property_Sale_Price
0,1,60,RL,65.000000,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.000000,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.000000,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.000000,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.000000,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2068,942,60,RL,72.056475,8755,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,6,2009,WD,Normal,214000
2069,943,90,RL,63.000000,7711,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,Oth,Abnorml,150000
2070,944,90,RL,313.000000,25000,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,143000
2071,945,20,RL,52.000000,14375,Pave,NaN,IR1,Lvl,NoSeWa,...,0,NaN,NaN,NaN,0,1,2009,COD,Abnorml,137500
2072,946,50,RM,98.000000,8820,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnWw,NaN,0,9,2009,WD,Normal,124900

In [15]:
x=property_data[['LotArea','YearBuilt','OverallQual','OverallCond','BedroomAbvGr','KitchenAbvGr','LowQualFinSF','BsmtFinSF2','GarageCars','GarageArea','YrSold','PoolArea','FullBath','TotalBsmtSF','GrLivArea','ScreenPorch','HalfBath','BsmtFullBath','2ndFlrSF']]#independent

In [16]:
y=property_data['Property_Sale_Price']#dependent(output)

In [17]:
print(x)

      LotArea  YearBuilt  OverallQual  OverallCond  BedroomAbvGr  \
0        8450       2003            7            5             3
1        9600       1976            6            8             3
2       11250       2001            7            5             3
3        9550       1915            7            5             3
4       14260       2000            8            5             4
...       ...        ...          ...          ...           ...
2068     8755       1936            8            4             3
2069     7711       1936            6            9             4
2070    25000       1983            4            6             4
2071    14375       1958            9            6             3
2072     8820       1890            9            9             2

      KitchenAbvGr  LowQualFinSF  BsmtFinSF2  GarageCars  GarageArea  YrSold  \
0                1             0           0           2         548    2008
1                1             0           0           2         460    2007
2                1             0           0           2         608    2008
3                1             0           0           3         642    2006
4                1             0           0           3         836    2008
...            ...           ...         ...         ...         ...     ...
2068             1             0           0           2         390    2009
2069             2             0           0           0           0    2007
2070             2             0           0           2         576    2007
2071             1             0         354           2         525    2009
2072             1           120           0           2         456    2009

      PoolArea  FullBath  TotalBsmtSF  GrLivArea  ScreenPorch  HalfBath  \
0            0         2          856       1710            0         1
1            0         2         1262       1262            0         0
2            0         2          920       1786            0         1
3            0         1          756       1717            0         0
4            0         2         1145       2198            0         1
...        ...       ...          ...        ...          ...       ...
2068         0         2          992       2060            0         1
2069         0         2         1440       1440            0         0
2070         0         2         1632       1632            0         0
2071         0         1          819       1344          233         0
2072         0         1         1088       1869            0         0

      BsmtFullBath  2ndFlrSF
0                1       854
1                0         0
2                1       866
3                1       756
4                1      1053
...            ...       ...
2068             1      1038
2069             2         0
2070             0         0
2071             0         0
2072             0       561

[2073 rows x 19 columns]

In [18]:
print(y)

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
2068    214000
2069    150000
2070    143000
2071    137500
2072    124900
Name: Property_Sale_Price, Length: 2073, dtype: int64

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
model=LinearRegression()

In [21]:
model.fit(x,y)

LinearRegression()

In [22]:
model.score(x,y)

0.7682307306892314

In [23]:
model.predict([[9874,1986,9,10,4,2,110,310,1,387,2000,0,2,999,1374,100,0,2,1000]])

array([148117.642739])

In [24]:
from sklearn.model_selection import train_test_split#import

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [26]:
model.fit(x_train,y_train)

LinearRegression()

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
lin_reg_mod=LinearRegression()

In [29]:
lin_reg_mod.fit(x_train,y_train)

LinearRegression()

In [30]:
pred=lin_reg_mod.predict(x_test)

In [31]:
pred

array([ 96318.96665059, 163600.39488778, 242981.34944226, 177266.80620281,
       103825.94594604, 178951.78908928, 106011.601313  , 220716.94351812,
       238514.47169032, 149845.81403285, 118720.96281732, 247694.2653479 ,
       310356.89267245, 180427.14232648, 225653.83677286, 258606.36282905,
       129660.98523861, 190954.50196215, 112930.31607639,  70007.90291278,
       211234.81118077, 200827.09240255, 129352.06825735, 195548.32606861,
       219127.92398765, 216869.98537777, 234848.6786444 ,  98388.98621064,
       245202.54916301, 149394.29853305, 273004.21711094, 205109.38317207,
       132412.0723919 , 268468.42930277, 158827.38627318, 128438.35964009,
       112214.75212179, 183135.89481149, 134289.66039284, 104225.43888874,
       216017.62546788, 152798.17115823, 139720.62740658,  62337.86559314,
       203914.01834649, 204461.06485121,  95551.92113496, 159281.83694928,
       109547.87965239, 211575.73664179,  88790.62647938, 241981.10506498,
       312833.35857558, 168165.06277802, 259623.40723245, 148475.55584547,
       271383.27829455, 136343.25473854, 154313.39808801, 127087.93282165,
       301734.58174829, 123945.47253885, 166632.00484897, 244285.40098821,
       132456.08034144,  95671.09367729, 195013.06271696, 207465.83811197,
       207380.35945329, 111564.81668567,  67388.58644143, 156231.61124145,
       273969.27903498, 146109.00834706, 270003.49973818, 208351.02308085,
       235245.69208353,  88573.97230474,  93488.09852802, 231024.42599643,
       205778.27558462, 130955.54222983, 131489.87085129, 336540.7600369 ,
       153835.35707325, 194531.60394946,  94383.43224844, 202249.45583863,
       189083.41631832, 217137.27085565, 251527.40638716, 302247.78936376,
        52943.71441048, 256315.05278613, 200360.32569125, 201748.98168722,
       345959.13416514, 198464.21394803, 226342.00999482,  88750.33998627,
       163357.7442459 , 197802.99037032, 176520.68629622, 124503.62920827,
       109235.62202722, 283719.84315089, 252355.79528932, 227397.49200763,
       123801.46420441, 200658.43417006, 226910.85059493,  87544.01643157,
       210621.01981552, 140206.21137436, 220370.91852723, 132036.09066796,
       157154.49654749, 281279.96633696, 200561.56250409, 201661.55664613,
        56171.98105811, 164845.12861165, 185627.97553189, 245956.15393239,
       221486.11945684, 206943.92141855, 213019.37854928, 231158.69294008,
        88426.00305212, 237760.74459261, 131516.31395353, 244278.89771052,
       126232.84731297, 263508.04941833,  70048.99525014, 122041.99592631,
        78043.59579664, 281375.36560874, 215583.95884978, 184145.53214023,
       110560.25304643, 159376.52489645, 135583.64315378, 205506.84740318,
       124743.28732086, 238215.6692703 , 211589.21731496,  96325.28250836,
       112519.14647149, 305531.66592811, 203232.40040728, 122621.89440165,
       186273.75470032, 138196.9249996 , 253577.33350108, 120411.12845331,
       116036.283847  , 228325.96564151, 244856.76002866, 106112.35583502,
        99990.17257675, 135439.88007815, 131857.25521018,  78400.96351896,
       225336.31049916, 150036.63915266, 180940.85166897, 310750.72376543,
       140670.00719961, 198959.34781019, 137052.06700478, 109039.45496783,
       218471.72250534, 205362.49586169, 227477.22941067, 211922.98782881,
       273045.60792895, 218209.68057679, 174478.09640065, 222486.21215775,
       112946.9761547 , 242892.7668071 , 173219.26293017, 217522.47181851,
       122839.65362127, 203347.38190671, 135804.9364518 , 169091.68352155,
       317230.71967514, 104853.67437553, 206664.61720829, 255662.71517494,
       280519.25564771, 160829.82138194, 216809.12394391, 223839.82747484,
       129306.86245005, 192781.48027812, 205993.03713606, 207622.32792119,
       213573.36070122, 150088.22326338, 221724.37948606, 200379.95315928,
       218238.29710792, 239622.46153295, 105331.94670968,  80920.70788521,
       197449.49502394, 189207.46245139, 261643.92440432, 128757.38881006,
       229694.1572446 , 128158.72238589, 121061.40438664, 251403.34885582,
       150746.34444293, 202810.37149301, 175740.42262643, 226476.02682921,
       253341.21123415, 172311.10607929, 229574.57705909, 228411.10270356,
       217140.57513159, 208721.06700719, 164078.02503904, 236079.95608668,
       124143.2633172 , 137886.91450884, 187781.91043216, 150770.91710538,
       211290.51802288,  96929.61209832, 150433.72751983, 191523.9759963 ,
       131928.82327875, 149973.73115235, 146954.60267822,  71292.07706115,
       295011.22132904, 204397.74474342,  73395.11160956, 258460.27503908,
       134625.10271608, 267727.4112115 , 156341.28683535,  99024.63308455,
       168211.9247988 , 174963.8081873 , 363521.05905865, 363427.52334507,
       208700.95320395, 164478.61079358, 245939.05245052, 164216.13599318,
       141404.08084411, 105827.86849386, 283632.90630903, 146502.98458372,
       212796.32956379, 125359.55240607, 286013.50031112, 265988.08467629,
       202822.98094203, 237373.29947667, 258967.17590772,  57252.35450956,
       356366.98709351, 143541.92079038, 202799.15355906, 147079.7520356 ,
       152572.12664625,  89181.63794133,  45813.44730957, 131600.1037326 ,
       139213.30602258, 145172.67156287, 111600.55586002, 212954.32461307,
       168473.43469892, 218763.60443934, 143079.2648838 , 249987.84606594,
       283274.14834858,  85969.74780941, 206425.9284184 ,  56793.39192877,
       176698.47036468, 120186.64999199, 170809.24595929, 254374.00309045,
       277541.10131849, 249698.4833199 ,  87487.58925317, 185655.38200288,
       194616.98662991, 102049.25332096, 129093.46800944, 106971.15261953,
       211774.61699072, 308645.14950442, 155613.21214739, 291456.13225403,
       192440.54745745, 144188.58467512, 153477.88275766,  99108.25831166,
        96443.01924496, 275642.06042453, 228809.18915252, 212072.01861362,
       249790.04720453, 114841.80661468, 111403.91651126,  47448.52159578,
       226759.79652657, 131696.18538502, 249835.20647451, 134332.81746752,
       219154.22761844, 203326.62425418,  93910.46167615, 170327.10446973,
       223385.41349769,  50146.72272781, 141810.72412229, 162804.092421  ,
        84850.58845664, 135613.53729368, 222697.82173961, 213214.30121292,
       103588.27317861, 255467.48693323, 163982.00667245, 205896.8409758 ,
       216289.35584785, 170284.34169379, 334972.8549393 , 140384.87947238,
       264990.38545756, 266878.97948043, 189082.61240911, 118700.32341611,
       104923.49020315, 133145.02273323, 182689.79396281, 116802.64535606,
       156465.11655056,  60380.73151384, 162962.9356779 , 175102.38956396,
        43137.20121987, 112886.0232425 , 171936.42903278, 105419.96181926,
       185481.56168749, 121668.1807586 , 127165.86687037, 195959.3969874 ,
       169060.23876537, 198639.29293117, 206128.62929841, 151253.97432454,
       167206.49241147, 183460.1502332 , 105467.20291682, 252346.86350348,
       225970.89200907, 244212.81604021, 187289.19363508, 253067.08673165,
       250296.53952949, 156269.78337567, 138837.94587526, 130963.02647117,
       120702.30011027, 123700.60265428,  77811.88803303,  68248.41995113,
       150021.97622697, 189842.12119042, 189448.17593408,  39642.1111373 ,
       309052.02575777, 228011.81627014, 256858.22384014, 268950.05897054,
       129386.78929094, 221698.6101705 , 237135.88161074, 216114.55255619,
       311654.14571427, 203171.16988205,  94307.38899441, 301626.50240418,
       109856.04208024, 118019.59420921, 185233.66880496,  32311.23173972,
       199915.26466595, 196149.37452707, 154987.16757815, 221265.56362805,
       287822.53503525, 178700.19791221, 204507.99135182, 122226.73607158,
       169554.99390808, 274735.24460338, 130904.09898527, 378797.39696825,
       163206.32791788, 237288.91856707, 183810.85739512, 186698.22245745,
       365325.69646582, 141974.63445396, 252365.0019147 , 287173.55037166,
       191273.60905873, 288003.19311841, 115618.13201632,  82646.82459808,
       243490.91290996,  98005.32416557, 131675.93478863, 207933.63695312,
       162482.18361893, 390495.57549408,  81693.36261043, 177273.1596136 ,
       202055.42919072, 183297.07362054, 325010.52338035, 265142.8606576 ,
       212246.7236934 , 150098.82746738, 156235.08829216, 174964.55396799,
       199839.04980876, 366702.2278699 , 156463.11266137, 204188.6501252 ,
       151442.15814433, 141507.19073862, 130307.43142087, 330126.44282703,
       108044.28342603, 126171.10261912, 169403.08156397,  79713.62570787,
       203279.31005726, 249691.10856246,  95218.34748012, 208311.14525149,
       183981.06652128, 200560.07139229, 182604.04405079, 154508.63887597,
       115771.10595241, 261755.3707039 , 128533.25541267,  92552.20602062,
       214620.38804343,  96090.53944602, 242397.56124027, 141979.93511024,
       201430.57238686, 198517.98351856, 181760.12337869, 275841.10705289,
       125471.19795324, 293562.05303018, 276759.33585488, 155112.70073607,
       126192.14553229, 124389.28428146, 173738.99003361, 148981.94707877,
       261090.91123084, 127060.59229446, 257018.17532188, 138541.5347376 ,
        19129.17266784, 292483.70861589, 246382.43082872, 108762.6433542 ,
       118044.47868214, 227603.38761573, 109525.07444596, 201162.7634028 ,
       248347.13398513, 184681.15101154, 107671.08205886, 210673.96800555,
       163758.72175364, 123754.30405936, 114795.78062418, 156723.72010317,
       154572.21864234, 209255.83337112, 181946.14858381, 196396.89780675,
       179171.36186043, 267297.90976261, 289811.51822301, 101003.41530738,
       123600.78721597, 312431.89305577, 215581.532757  , 215981.87016143,
       145981.08178896, 279106.60392571, 187483.1739183 , 119962.09480017,
       225395.46159618, 143498.04818857, 199922.92930193])

In [32]:
import numpy as np
from sklearn import metrics
test_set_r2=metrics.r2_score(y_test,pred)

In [33]:
print(test_set_r2)

0.7726026078828557

In [34]:
lin_reg_mod.predict([[9874,1986,9,10,4,2,110,310,1,387,2000,0,2,999,1374,100,0,2,1000]])

array([148462.70870764])

In [35]:
import seaborn as sb

In [36]:
model.coef_

array([ 2.60329399e-01,  2.84942373e+02,  4.29769811e+03,  3.57182228e+03,
       -9.70006934e+03, -4.48668529e+04, -4.86727397e+01, -1.96543734e+01,
        1.76202527e+04,  6.18749559e+00, -3.62574602e+02, -1.44707263e+02,
        1.42232376e+04,  3.30689396e+01,  7.92933955e+01,  5.31769016e+01,
        7.04436570e+03,  1.34500131e+04, -7.95257673e+00])